
name: Test automation workflow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadLess=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
          name: automation-logs
          path: logs/
          
    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
          name: Screenshots
          path: screenshots/      

    - name: Upload HTML Reports as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Reports
        path: report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html  public/extent-reports
        cp -R screenshot/ public/extent-reports/screenshot/
        ls -l

        
    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{ secrets.Token }}
        clean: true


      
    
